server:
  port: 8882
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_exam?serverTimezone=UTC
    username: root
    password: shanyunbiao
  flyway:
    baseline-on-migrate: true
mybatis:
  type-aliases-package: true
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
